/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import models.TelefoneEmail;
import models.Contato;
import models.TelefoneEmail.Tipo;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import utils.Validator;

/**
 *
 *
 */
public class Principal extends JFrame {

    private Contato contatoDAO;
    private TelefoneEmail telmailDAO;

    public Principal() {
        initComponents();
        this.contatoDAO = new Contato();
        this.telmailDAO = new TelefoneEmail();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radtelmailCadastro = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        botaoCadastrar = new javax.swing.JButton();
        txtSobrenome = new javax.swing.JTextField();
        txtDia = new javax.swing.JTextField();
        txtMes = new javax.swing.JTextField();
        txtAno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        painel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblContato = new javax.swing.JTable();
        btnRemover = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtAlteraNome = new javax.swing.JTextField();
        btnAlterar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtAlteraSobrenome = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTelMail = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtRotulocadastro = new javax.swing.JTextField();
        txtValorcadastro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        radMail = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnCadatroTelMail = new javax.swing.JButton();
        txtAlteraRotulo = new javax.swing.JTextField();
        txtAlteraValor = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Minha Primeira Tela");
        setResizable(false);

        lblNome.setText("Nome");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        lblEndereco.setText("Sobrenome");

        lblTitulo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblTitulo.setText("Cadastro de Contato");

        botaoCadastrar.setText("Cadastrar");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        txtSobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSobrenomeActionPerformed(evt);
            }
        });

        txtDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaActionPerformed(evt);
            }
        });

        jLabel2.setText("Data de Nascimento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSobrenome))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(20, 20, 20)
                        .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botaoCadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(656, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndereco)
                    .addComponent(txtSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoCadastrar)
                .addContainerGap(268, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro", jPanel1);

        painel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                painelComponentShown(evt);
            }
        });

        tblContato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdContato", "Nome", "Sobrenome", "Data de Nascimento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblContato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblContatoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblContato);

        btnRemover.setText("Remover Contato");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        txtAlteraNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlteraNomeActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        jLabel6.setText("Sobrenome");

        txtAlteraSobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlteraSobrenomeActionPerformed(evt);
            }
        });

        tblTelMail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Telefone/Email", "Rotulo", "Valor", "Tipo", "IdContato"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTelMail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTelMailMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblTelMail);

        jLabel7.setText("Rotulo");

        txtRotulocadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRotulocadastroActionPerformed(evt);
            }
        });

        jLabel8.setText("Valor");

        jLabel9.setText("Tipo");

        radtelmailCadastro.add(radMail);
        radMail.setText("E-mail");

        radtelmailCadastro.add(jRadioButton2);
        jRadioButton2.setText("Telefone");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel10.setText("Rotulo");

        jLabel11.setText("Valor");

        btnCadatroTelMail.setText("Cadastrar Telefone/Email");
        btnCadatroTelMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadatroTelMailActionPerformed(evt);
            }
        });

        jButton3.setText("Alterar Telefone/Email");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtValorcadastro)
                                .addComponent(txtRotulocadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelLayout.createSequentialGroup()
                                .addComponent(radMail)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2))))
                    .addComponent(btnCadatroTelMail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAlteraValor)
                            .addComponent(txtAlteraRotulo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLayout.createSequentialGroup()
                            .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(painelLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(29, 29, 29)
                                    .addComponent(txtAlteraNome, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtAlteraSobrenome, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                        .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnRemover)
                            .addGap(76, 76, 76))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLayout.createSequentialGroup()
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelLayout.createSequentialGroup()
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtAlteraNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtAlteraSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAlterar)
                            .addComponent(btnRemover))
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelLayout.createSequentialGroup()
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRotulocadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValorcadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(radMail)
                            .addComponent(jRadioButton2))
                        .addGap(18, 18, 18)
                        .addComponent(btnCadatroTelMail)))
                .addGap(18, 18, 18)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtAlteraRotulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtAlteraValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listas e alterções", painel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1223, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed

        String nome = txtNome.getText();
        String sobrenome = txtSobrenome.getText();
        int ano = Integer.parseInt(txtAno.getText());
        int mes = Integer.parseInt(txtMes.getText());
        int dia = Integer.parseInt(txtDia.getText());

        Date dataNascimento = new Date(ano, mes, dia);
        this.contatoDAO.create(nome, sobrenome, dataNascimento);
        JOptionPane.showMessageDialog(this, "Cadastro de contato efetuado com sucesso!");
        atualizaTabelaContato();
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void txtSobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSobrenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSobrenomeActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void txtRotulocadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRotulocadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRotulocadastroActionPerformed

    private void tblTelMailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTelMailMouseClicked
                                     
        int linhaSelecionada = this.tblTelMail.getSelectedRow();

        String rotulo = (String) this.tblTelMail.getValueAt(linhaSelecionada, 1);
        String valor = (String) this.tblTelMail.getValueAt(linhaSelecionada, 2);

        txtAlteraRotulo.setText(rotulo);
        txtAlteraValor.setText(valor);
        
    }//GEN-LAST:event_tblTelMailMouseClicked

    private void txtAlteraSobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlteraSobrenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlteraSobrenomeActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        int linhaSelecionada = this.tblContato.getSelectedRow();
        String id = (String) this.tblContato.getValueAt(linhaSelecionada, 0);

        String nome = this.txtAlteraNome.getText();
        String sobrenome = this.txtAlteraSobrenome.getText();

        
        this.contatoDAO.update(id,nome,sobrenome);
        
        JOptionPane.showMessageDialog(this, "Nome e sobrenome alterados com sucesso"); 
        this.txtAlteraNome.setText("");
        this.txtAlteraSobrenome.setText("");
        
        
        atualizaTabelaContato();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void txtAlteraNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlteraNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlteraNomeActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        int linhaSelecionada = this.tblContato.getSelectedRow();

        String id = (String) this.tblContato.getValueAt(linhaSelecionada, 0);
        
        try {
            this.contatoDAO.remover(id);
            JOptionPane.showMessageDialog(this, "Contato removido");
            atualizaTabelaContato();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao deletar"); 
        }
        
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void tblContatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblContatoMouseClicked
        int linhaSelecionada = this.tblContato.getSelectedRow();

        String nome = (String) this.tblContato.getValueAt(linhaSelecionada, 1);
        String sobrenome = (String) this.tblContato.getValueAt(linhaSelecionada, 2);

        txtAlteraNome.setText(nome);
        txtAlteraSobrenome.setText(sobrenome);
        

        atualizaTabelaTelefoneEmail();
  
    }//GEN-LAST:event_tblContatoMouseClicked

    private void btnCadatroTelMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadatroTelMailActionPerformed

        String rotulo = txtRotulocadastro.getText();
        String valor = txtValorcadastro.getText();

        boolean email = radMail.isSelected();

        int linhaSelecionada = this.tblContato.getSelectedRow();
        String contatoId = (String) this.tblContato.getValueAt(linhaSelecionada, 0);

        Tipo tipo;
        if (email){
            tipo = Tipo.EMAIL;
        }else{
            tipo = Tipo.TELEFONE;
        }
        
        boolean isValorValid = true;
        
        if (tipo == Tipo.EMAIL) {
            //valida email
            if (!Validator.isValidEmail(valor)) {
                JOptionPane.showMessageDialog(this, "Formato de email inválido. Ex: abc@email.com");
                isValorValid = false;
            }
        } else {
            // valida tel
            if (!Validator.isValidTelefone(valor)) {
                isValorValid = false;
                JOptionPane.showMessageDialog(this, "Formato de telefone inválido Ex: (49) 00000-0000");
            }
        }
        
        if (isValorValid) {
            try {
                telmailDAO.create(rotulo,  valor,  tipo, contatoId);
                JOptionPane.showMessageDialog(this, "Cadastro de telefone/email efetuado com sucesso!");
                txtRotulocadastro.setText("");
                txtValorcadastro.setText("");
            } catch(Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao cadastrar Telefone/Email");
            }

            atualizaTabelaTelefoneEmail();
        }
        
    }//GEN-LAST:event_btnCadatroTelMailActionPerformed

    private void txtDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = this.tblTelMail.getSelectedRow();
        String id = (String) this.tblTelMail.getValueAt(linhaSelecionada, 0);

        String rotulo = this.txtAlteraRotulo.getText();

        String valor = this.txtAlteraValor.getText();

        telmailDAO.update(id, rotulo, valor);
        
        
        JOptionPane.showMessageDialog(this, "Rotulo e valor alterados com sucesso");

    }//GEN-LAST:event_jButton3ActionPerformed

    private void painelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_painelComponentShown
        // TODO add your handling code here:
        atualizaTabelaContato();
    }//GEN-LAST:event_painelComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadatroTelMail;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel painel;
    private javax.swing.JRadioButton radMail;
    private javax.swing.ButtonGroup radtelmailCadastro;
    private javax.swing.JTable tblContato;
    private javax.swing.JTable tblTelMail;
    private javax.swing.JTextField txtAlteraNome;
    private javax.swing.JTextField txtAlteraRotulo;
    private javax.swing.JTextField txtAlteraSobrenome;
    private javax.swing.JTextField txtAlteraValor;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRotulocadastro;
    private javax.swing.JTextField txtSobrenome;
    private javax.swing.JTextField txtValorcadastro;
    // End of variables declaration//GEN-END:variables

    public void atualizaTabelaContato() {
        String[] campos = {"Id Contato", "Nome", "Sobrenome", "Data de Nascimento"};
        DefaultTableModel dtm = new DefaultTableModel(campos, 0);
        this.tblContato.setModel(dtm);

        List<Contato> contatos = this.contatoDAO.consultarContatos();
        
        for (int i = 0; i < contatos.size(); i++) {;
            Contato c = contatos.get(i);
            
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");  
            String strDate = formatter.format(c.getDataNascimento());  
    
            String[] valores = {c.getId(),c.getNome(), c.getSobrenome(),strDate};
            dtm.addRow(valores);
        }
    }
    
    public void atualizaTabelaTelefoneEmail() {
        int linhaSelecionada = this.tblContato.getSelectedRow();

        String idcontato = (String) this.tblContato.getValueAt(linhaSelecionada, 0);

        String[] campos = {"Id Tel/Mail", "Rotulo", "Valor", "Tipo", "Id Contato"};
        DefaultTableModel dtm = new DefaultTableModel(campos, 0);
        this.tblTelMail.setModel(dtm);

        List<TelefoneEmail> telmail = this.telmailDAO.consultarTelefoneEmail(idcontato);
        /**
         * ****************************
         * presisa-se do metodo consultarContatos que retorne todos os telefones
         * e e-mails do idcontato relacionado
         *
         */
        for (int i = 0; i < telmail.size(); i++) {;;
            TelefoneEmail t = telmail.get(i);
            String tipo;
            if(t.getTipo() == Tipo.EMAIL){
                tipo = "Email";
            }else{
                tipo = "Telefone";
            }
             
    
            String[] valores = {t.getId(),t.getRotulo(), t.getValor(),tipo,idcontato};
            dtm.addRow(valores);
        }
    }
}
